### ISSUE TITLE
Developer theme

### ISSUE THREAD

**Issue by sanyarnd** [Quicksaver/Tab-Groups#415]
Not much time ago tab groups had broken color scheme and now there's an issue with dev's theme readability.

with dev theme:
![](https://s22.postimg.org/hyiizpdwx/2016_09_27_140612.png)

without dev theme:
![](https://s22.postimg.org/82hg0284x/2016_09_27_140625.png)

setup:
FF ESR 45 x86
Developer theme
Tree Style Tab

**Comment by Quicksaver** [comment]
I think this is better fixed in Tile Tabs, it's already doing all sorts of magic with lightweight themes to button labels, it will be much more easily fixed there for the developer edition theme as well. Have you tried contacting its developer about it?

**Comment by sanyarnd** [comment]
I did not. 
Actually, why should I contact Tile Tabs?

**Comment by Quicksaver** [comment]
What I meant was, Tile Tabs is already applying some special styling to text in buttons (including the Tab Groups button) based on the current theme. It's not applying it for the Developer Theme though, I'm sure they would like to do that for that theme as well, as this seems to affect anything that adds text-related items to the tabs bar, not just the Tab Groups button.

**Comment by Quicksaver** [comment]
I meant Tree Style Tab, not Tile Tabs... That's the fourth time I make that mistake today, I'm sorry for the confusion.

**Comment by Quicksaver** [comment]
And you know what, nevermind, turns out it's a much easier fix from my side than I had expected.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix the groups label with TST. Please give it a try and let me know how it works for you.

**Comment by sanyarnd** [comment]
Works fine.

[result](https://postimg.org/image/mgj19n817/)

Although it'd be good to pick color (I'm not really aware of web-programming to customize it myself).
Currently I'm using modified .css (stylish addon) for [darker BG on pages.](https://userstyles.org/styles/119214/ft-deepdark-ugoboom-mod-fixed), if you may give me any hints how to redefine color for exactly this button, I'll be grateful.

**Comment by Quicksaver** [comment]
Try something like this, it's not perfect but it should do the trick:
```CSS
#tabGroups-tabview-button {
  -moz-appearance: none;
  background:  #1E1E1E !important;
  color: rgb(180,180,180) !important;
  border: none !important;
  box-shadow: none !important;
  min-height: 26px !important;
}

#tabGroups-tabview-button:-moz-any(:hover,:active) {
  background:  #1E1E1E !important;
  color: rgb(0,173,238) !important;
}
```
